version: '3'

services:
  db:
    image: 'mysql'
    environment:
      MYSQL_USER: apirest
      MYSQL_PASSWORD: apipass 
      MYSQL_DATABASE: restful_store
      MYSQL_ROOT_PASSWORD: root_pass 
    depends_on:
      - apirest
    volumes:
      - ./db:/var/lib/mysql 

  apirest:
    command: flask run --host=0.0.0.0
    env_file:
      - ./.env.dev
    ports:
      - "5000:5000"
    volumes:
      - ./api/code:/app
